vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        thumbnails:
            uri_prefix: /uploads/thumbnails
            upload_destination: '%kernel.project_dir%/public/uploads/thumbnails'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true