version: '3.7'
services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: betbunk
    volumes:
      - db-data:/var/lib/postgresql/data/
  adminer:
    image: adminer
    ports:
      - 18080:8080
volumes:
  db-data:
    driver: local